apiVersion: v1
kind: Secret
metadata:
  name: pccs-tls
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
type: Opaque
data:
  file.crt: {{ .Values.pccsTlsKeyPair.certificate | b64enc | quote }}
  private.pem: {{ .Values.pccsTlsKeyPair.privateKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pccs-config
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
type: Opaque
data:
  default.json: {{ tpl (.Files.Get "config/default.json") . | b64enc | quote }}
---
{{- if .Values.imagePullSecrets.enabled }}
{{- $registry := .Values.imagePullSecrets.data.registry }}
{{- $username := .Values.imagePullSecrets.data.username }}
{{- $password := .Values.imagePullSecrets.data.password }}
{{- $email := .Values.imagePullSecrets.data.email | default "" }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $dockerConfig := printf
    "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}"
    $registry $username $password $email $auth | b64enc }}

apiVersion: v1
kind: Secret
metadata:
  name: pccs-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig }}
{{- end }}
